version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
  dev:
    depends_on: nginx
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
  prod:
    depends_on: nginx
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000

